userDescription = """
### Dành cho user

* **Login**: User Login to the system with phone number and token (**POST**)
* **Update user info**: User can update their profile information (**PUT**)
* **User add location**: User can add location to their profile (**POST**)
* **User update location**: User can update location to their profile (**PUT**)
* **User delete location**: User can delete location to their profile (**DELETE**) (Chưa có)
* **User get list location**: User can get list location to their profile (**GET**)
* **User get point**: User can get cumulative points (Điểm tích lũy) (**GET**)

==============================================================================================

### Dành cho staff
* **Staff Get List User while typing phone number**: Staff can get list user while typing phone number
* **Staff Get User By Id**: Staff can get user by id
* **Staf Lock User by User ID**: Staff can lock user by user id

"""

loginDescription = """
User Login to the system with phone number and token
(token is generated by firebase)
"""

userUpdateDescription = """
User can update their profile information
- fullname: fullname of user
- address: address of user
- dob: date of birth of user
- email: email of user
"""

getListUserDescription = """
Staff can search user by phone number with params
"""

userAddLocationDescription = """
User can add location to their profile
- fullname: fullname of user
- phone: phone of user
- title_location (string): title of location
- type_location (string): type of location
- address (string): address of location
- district (string): district of location
- city (string): city of location
- country (string): country of location
- is_active (boolean): Active or not this location
"""

userUpdateLocationDescription = """
User can update location to their profile by location_id params

- title_location (string): title of location
- type_location (string): type of location
- address (string): address of location
- district (string): district of location
- city (string): city of location
- country (string): country of location
- is_active (boolean): Active or not this location

"""

userGetListLocationDescription = """
User can get list location to their profile
"""

lockUserDescription = """
Staff can lock user by user id
"""

getUserByIdDescription = """
Staff can get user by id
"""

userGetPointDescription = """
User can get cumulative points (Điểm tích lũy)
"""
